-- Seed: last year's vendors + booth assignments (run once in Supabase SQL editor).
-- Idempotent: new booths use ON CONFLICT DO NOTHING; vendors insert skips names
-- that already exist; the booth mapping re-applies cleanly if run again.
-- Existing booth coordinates are never touched.

-- 1. Directory vendors may have no contact email; vendors.contact_email was
--    NOT NULL (intended for the public apply form), so relax it for imports.
ALTER TABLE vendors ALTER COLUMN contact_email DROP NOT NULL;

-- 2. Add booths for exhibitors that had no matching booth on the current map
--    (New York Sash, First Source, Deerfield Place, Mohawk Valley Spray Foam).
--    Reposition these in /admin/booths if the placement needs tweaking.
INSERT INTO booths (booth_number, coordinates, floor, status) VALUES
  ('34-36', '{"x1":1240,"y1":1485,"x2":1412,"y2":1610}', 'Ground Level – Rink 3', 'available'),
  ('177-179', '{"x1":70,"y1":535,"x2":140,"y2":735}', 'Ground Level – Rink 2', 'available'),
  ('H1', '{"x1":520,"y1":1020,"x2":650,"y2":1085}', 'Ground Level – Rink 2', 'available'),
  ('H2', '{"x1":660,"y1":1020,"x2":790,"y2":1085}', 'Ground Level – Rink 2', 'available')
ON CONFLICT (booth_number) DO NOTHING;

-- 3. Insert vendor records (skip any that already exist by company_name).
INSERT INTO vendors (company_name, website_url, industry_category)
SELECT v.company_name, v.website_url, v.industry_category
FROM (VALUES
  ('Abbas Acres', 'https://www.abbasacresfarm.com/', 'Tasting'),
  ('Acme Pool and Spa', NULL, 'Shopping'),
  ('AJB Property Maintenance', 'https://ajbpropertymaintenance.com/', 'Services'),
  ('Amber Water Pros', 'http://amberwaterpros.com/', 'Shopping'),
  ('AmeriCU Credit Union', 'https://www.americu.org/', 'Services'),
  ('Awning''s & Canopy''s by Sure Seal', 'https://www.suresealwi.com/', 'Exterior Remodeling'),
  ('B&K Fencing', 'https://bandkfencing.com/', 'Exterior'),
  ('Basement Waterproofing Pros, LLC', 'http://www.basementwaterproofingprofessionals.com/', 'Interior Remodeling'),
  ('Bass Pro Shops Utica', NULL, 'Shopping'),
  ('Bath Pros LLC', 'https://bathpros.org/', 'Interior Remodeling'),
  ('Beltone Hearing Care Center', 'https://beltonesound.com/', 'Services'),
  ('C. Michael Exteriors, Inc.', 'https://www.cmichaelexteriors.com/', 'Exterior Remodeling'),
  ('Cabinets To Go', 'http://www.cabinetstogo.com', 'Interior Remodeling'),
  ('Cheese Filled Company', 'http://cheesefilledcompany.com', 'Shopping'),
  ('Chocolate Moonshine', 'https://www.chocolatemoonshine.com/', 'Tasting'),
  ('Clinton Tractor', 'https://www.clintontractor.net/', 'Outdoor'),
  ('CNY Sunrooms & Windows', 'http://CNYSunroomsandWindows.com', 'Exterior Remodeling'),
  ('CNY''s Open House', NULL, 'Services'),
  ('Comfort Windows and Doors', NULL, 'Exterior Remodeling'),
  ('Cooper''s Daughter Spirits', NULL, 'Tasting'),
  ('Cosimano E Ferrari, LLC', 'http://www.cosimanoferrari.com/', 'Tasting'),
  ('Country Suburban', 'http://countrysuburbanhvac.com/', 'HVAC'),
  ('Curtis Lumber', 'https://www.curtislumber.com/', 'Exterior Remodeling'),
  ('Cutco', 'https://www.cutco.com/', 'Shopping'),
  ('Decked by Tailored', 'https://www.deckedbytailored.com/', 'Exterior Remodeling'),
  ('Deerfield Place', 'https://www.deerfieldplaceutica.com/', 'Housing'),
  ('Destination KIA of Utica', 'https://www.destinationkiaofutica.com/', 'Shopping'),
  ('Dogwatch of Upstate NY', NULL, 'Services'),
  ('Energy Savers', 'https://energysaverscny.com', 'Services'),
  ('Faith Outdoors LLC', NULL, 'Advertising'),
  ('Fellowship of Christian Farmers', 'http://fcfi.org/', 'Non-Profit'),
  ('Fine Line Borders', 'https://finelineborders.com', 'Outdoor'),
  ('First Source Federal Credit Union (Kids Zone)', 'https://fsource.org/', 'Services'),
  ('Floor and Wall Remedies and More LLC', 'https://floorwallremedies.com/', 'Shopping'),
  ('Fortscapes Solar INC.', 'http://www.fortscapessolar.com/', 'Solar'),
  ('Four Fights Distilling', NULL, 'Tasting'),
  ('Fred F. Collis & Sons', 'https://fredfcollis.com/', NULL),
  ('GoNetspeed', 'https://www.gonetspeed.com/', 'Services'),
  ('Graves Brothers Home Improvement', 'http://www.gravesbros.com/', 'Exterior Remodeling'),
  ('Gutter Tech Enterprise', NULL, 'Exterior Remodeling'),
  ('Holbrook Heating Inc.', 'http://www.holbrookheating.com/', 'HVAC'),
  ('Home Heat', 'https://herculesheat.com/', 'Shopping'),
  ('Insurance Advisors', 'https://InsuranceAdvantageNY.com', 'Financial Services'),
  ('Invisible Fence Brand', 'https://www.invisiblefence.com/', 'Exterior Remodeling'),
  ('Java Farm Supply Inc.', 'http://www.javafarmsupply.com/', 'Shopping'),
  ('Jessica''s Sweet Treats', NULL, 'Tasting'),
  ('Joe Tahans Furniture & Ashley Home Store', NULL, 'Shopping'),
  ('John''s Clean-Outs and Property Preservation, Inc.', 'https://www.jcoandpropertypreservation.com/', 'Services'),
  ('KD Homes', 'http://kdhomesny.com/', 'Builder'),
  ('Lawn & Order Landscape LLC', NULL, 'Outdoor'),
  ('LeafFilter Gutter Protection', 'https://www.leaffilter.com/', 'Exterior Remodeling'),
  ('LeafGuard', 'http://www.leafguard.com/', 'Exterior Remodeling'),
  ('Lincoln Davies', 'https://lincolndavies.com/', 'Exterior Remodeling'),
  ('Lowes New Hartford', 'https://lowes.com', 'Shopping'),
  ('M. Wheelock Disposal', 'https://wheelockdisposal.com/', 'Services'),
  ('Melo Roofing Inc', 'https://meloroofing.com', 'Exterior Remodeling'),
  ('Michael White Contracting & All County Chip Seal', 'https://www.facebook.com/share/1DMdHzpncU/?mibextid=wwXIfr', 'Services'),
  ('Mirabito Energy Products', 'https://mirabito.com/', 'Services'),
  ('Mohawk Valley Spray Foam', NULL, NULL),
  ('Mosquito Authority', NULL, 'Services'),
  ('Mr. Squeeze Lemonade', 'https://lemonade.com', 'Tasting'),
  ('New York Sash', 'http://newyorksash.com/', 'Exterior Remodeling'),
  ('Norwex', 'https://norwex.com/rebeccakinney', 'Shopping'),
  ('Notre Dame Jr/Sr High NJROTC', NULL, 'Non-Profit'),
  ('Notre Dame Schools', 'http://www.notredameutica.org/', 'Non-Profit'),
  ('NP Environmental LLC', 'http://www.npenvironmental.com/', 'HVAC'),
  ('Oneida County Furnace', 'https://oneidacountyfurnace.com/', 'HVAC'),
  ('Oneida County Sheriffs Office', 'https://sheriff.oneidacountyny.gov', 'Services'),
  ('Oneida County Tourism', 'https://www.oneidacountytourism.com/', 'Non-Profit'),
  ('Oneida Floor Company', 'https://oneidafloor.com/', 'Interior Remodeling'),
  ('Patio Enclosures', 'https://www.patioenclosures.com/', 'Exterior'),
  ('Pella Windows and Doors', 'https://www.pella.com/', 'Exterior Remodeling'),
  ('Platinum Epoxy', 'https://platinum-epoxy.com/', 'Services'),
  ('PlugPV LLC', NULL, 'Solar'),
  ('Proctor Baseball', NULL, 'Non-Profit'),
  ('Pure Water Source', 'http://www.purewatersourceny.com/', 'Services'),
  ('Quality Home Products', 'https://qualityhomeproducts.net/', 'Services'),
  ('Renewal By Anderson of CNY', 'http://rbaofcny.com/', 'Exterior Remodeling'),
  ('Renovation Revival', 'https://www.facebook.com/share/1GBez1A3ZC/?mibextid=wwXIfr', 'Remodeling'),
  ('Rome Bath Remodeling', 'https://romebathremodeling.com/', 'Interior'),
  ('Sauna King USA', 'https://saunakingusa.com/', 'Shopping'),
  ('Scape Solutions LLC', 'https://www.scapesolutions315.com/', 'Outdoor'),
  ('Scentsy', 'https://denisebest.scentsy.us/', 'Shopping'),
  ('Seamless Gutter and Supply', 'https://gutterprony.com/', 'Exterior Remodeling'),
  ('Seas the Day SCUBA LLC', 'http://www.seasthedayscuba.net/', 'Services'),
  ('Sentinel Media Company', 'https://romesentinel.com', 'Services'),
  ('Short & Sweet Treats', 'https://www.facebook.com/shortandsweettreatsNY', 'Tasting'),
  ('Smith''s Garage Doors', 'https://smithsgaragedoorsandwindow.com/', 'Exterior Remodeling'),
  ('Solutions Empire LLC', 'https://www.solutionsempirellc.com/', 'Services'),
  ('Spacey Tracys Pickles INC', NULL, 'Tasting'),
  ('Standard Heating, Cooling & Insulating', 'https://www.standardco.com/', 'HVAC'),
  ('Stellar Roofing', 'https://stellarroofing.com/', 'Exterior Remodeling'),
  ('Superior Sleep Experience', 'http://www.supsleep.com/', 'Shopping'),
  ('Sure Seal Window Installations', 'https://www.suresealwi.com/', 'Exterior Remodeling'),
  ('T3 Building & Restoration', 'https://t3buildingllc.com/', 'Exterior Remodeling'),
  ('TAT2 Spirits, LLC', 'https://tat2spirits.com', 'Tasting'),
  ('The Mad Pickle Company', 'https://www.themadpicklecompany.com/', 'Tasting'),
  ('The Neighborhood Center', 'https://www.neighborhoodctr.org/', 'Non-Profit'),
  ('The Roofing Standard LLC', 'https://www.theroofingstandard.com/', 'Services'),
  ('Thousand Islands Winery', 'http://thousandislandswinery.com/', 'Tasting'),
  ('Timberland Fence', 'https://timberlandfenceandland.com/', 'Outdoor'),
  ('T-Mobile', 'https://t-mobile.com/', 'Services'),
  ('Tru-Line Hardwood Flooring', 'https://www.trulineflooring.com/', 'Interior Remodeling'),
  ('Tupperware', NULL, 'Tasting'),
  ('Uniquely Yours', 'https://www.uyinteriors.com/', 'Interior Remodeling'),
  ('Upstate Spray Foam Insulation', 'http://upstatesprayfoam.com/', 'Insulation'),
  ('Utica Gutters', 'https://www.uticagutters.com/', 'Exterior Remodeling'),
  ('W&B New York', NULL, 'Shopping'),
  ('Weis Vineyards', 'http://www.weisvineyards.com/', 'Tasting'),
  ('WellsServices Inc.', 'https://www.wellsservices.net/', 'Services'),
  ('Wish Fairy', 'https://www.facebook.com/TheWishFairyBooks', 'Shopping'),
  ('Witch''s Wicked Treats', NULL, 'Tasting'),
  ('Woodford Bros., Inc.', 'https://woodfordbros.com', 'Exterior Remodeling'),
  ('Yorkville Framing & Supply Co.', 'https://yorkvilleframing.com', 'Shopping')
) AS v(company_name, website_url, industry_category)
WHERE NOT EXISTS (SELECT 1 FROM vendors ex WHERE ex.company_name = v.company_name);

-- 4. Assign vendors to booths by booth_number (marks them sold).
UPDATE booths b
SET vendor_id = ve.id, status = 'sold', updated_at = NOW()
FROM (VALUES
  ('172', 'Abbas Acres'),
  ('43-45, 25-27', 'Acme Pool and Spa'),
  ('126', 'AJB Property Maintenance'),
  ('75-78', 'Amber Water Pros'),
  ('66', 'AmeriCU Credit Union'),
  ('98', 'Awning''s & Canopy''s by Sure Seal'),
  ('7-9', 'B&K Fencing'),
  ('131', 'Basement Waterproofing Pros, LLC'),
  ('169', 'Bass Pro Shops Utica'),
  ('54', 'Bath Pros LLC'),
  ('56', 'Beltone Hearing Care Center'),
  ('82-83', 'C. Michael Exteriors, Inc.'),
  ('52', 'Cabinets To Go'),
  ('33', 'Cheese Filled Company'),
  ('116', 'Chocolate Moonshine'),
  ('141-142', 'Clinton Tractor'),
  ('151-153', 'Clinton Tractor'),
  ('154', 'Clinton Tractor'),
  ('128', 'CNY Sunrooms & Windows'),
  ('5-6', 'CNY''s Open House'),
  ('124-125', 'Comfort Windows and Doors'),
  ('174', 'Cooper''s Daughter Spirits'),
  ('181', 'Cosimano E Ferrari, LLC'),
  ('63-65', 'Country Suburban'),
  ('150', 'Curtis Lumber'),
  ('157', 'Cutco'),
  ('15', 'Decked by Tailored'),
  ('H1', 'Deerfield Place'),
  ('187-194', 'Destination KIA of Utica'),
  ('197', 'Dogwatch of Upstate NY'),
  ('94-95', 'Energy Savers'),
  ('55', 'Faith Outdoors LLC'),
  ('165', 'Fellowship of Christian Farmers'),
  ('16', 'Fine Line Borders'),
  ('177-179', 'First Source Federal Credit Union (Kids Zone)'),
  ('20', 'Floor and Wall Remedies and More LLC'),
  ('79-80', 'Floor and Wall Remedies and More LLC'),
  ('73', 'Fortscapes Solar INC.'),
  ('120', 'Four Fights Distilling'),
  ('46-47', 'Fred F. Collis & Sons'),
  ('114', 'GoNetspeed'),
  ('101', 'Graves Brothers Home Improvement'),
  ('112', 'Gutter Tech Enterprise'),
  ('129-130', 'Holbrook Heating Inc.'),
  ('10-11', 'Home Heat'),
  ('115', 'Insurance Advisors'),
  ('67', 'Invisible Fence Brand'),
  ('134-137', 'Java Farm Supply Inc.'),
  ('146', 'Jessica''s Sweet Treats'),
  ('159-163', 'Joe Tahans Furniture & Ashley Home Store'),
  ('200-201', 'John''s Clean-Outs and Property Preservation, Inc.'),
  ('81', 'KD Homes'),
  ('185', 'Lawn & Order Landscape LLC'),
  ('39', 'LeafFilter Gutter Protection'),
  ('158', 'LeafGuard'),
  ('12-13', 'Lincoln Davies'),
  ('198-199', 'Lowes New Hartford'),
  ('74', 'M. Wheelock Disposal'),
  ('3-4', 'Melo Roofing Inc'),
  ('103-104', 'Michael White Contracting & All County Chip Seal'),
  ('202', 'Mirabito Energy Products'),
  ('H2', 'Mohawk Valley Spray Foam'),
  ('37', 'Mosquito Authority'),
  ('145', 'Mr. Squeeze Lemonade'),
  ('34-36', 'New York Sash'),
  ('119', 'Norwex'),
  ('166', 'Notre Dame Jr/Sr High NJROTC'),
  ('69', 'Notre Dame Schools'),
  ('184', 'NP Environmental LLC'),
  ('72', 'Oneida County Furnace'),
  ('164', 'Oneida County Sheriffs Office'),
  ('100', 'Oneida County Tourism'),
  ('48', 'Oneida Floor Company'),
  ('28', 'Patio Enclosures'),
  ('50', 'Pella Windows and Doors'),
  ('60-62', 'Platinum Epoxy'),
  ('156', 'PlugPV LLC'),
  ('22', 'Proctor Baseball'),
  ('57', 'Pure Water Source'),
  ('180', 'Quality Home Products'),
  ('87-88', 'Renewal By Anderson of CNY'),
  ('29', 'Renovation Revival'),
  ('21', 'Rome Bath Remodeling'),
  ('99', 'Sauna King USA'),
  ('68', 'Scape Solutions LLC'),
  ('183', 'Scentsy'),
  ('96', 'Seamless Gutter and Supply'),
  ('14', 'Seas the Day SCUBA LLC'),
  ('51', 'Sentinel Media Company'),
  ('182', 'Short & Sweet Treats'),
  ('84', 'Smith''s Garage Doors'),
  ('41-42', 'Solutions Empire LLC'),
  ('91', 'Spacey Tracys Pickles INC'),
  ('58-59', 'Standard Heating, Cooling & Insulating'),
  ('85-86', 'Stellar Roofing'),
  ('133', 'Superior Sleep Experience'),
  ('97', 'Sure Seal Window Installations'),
  ('170', 'T3 Building & Restoration'),
  ('121', 'TAT2 Spirits, LLC'),
  ('118', 'The Mad Pickle Company'),
  ('176', 'The Neighborhood Center'),
  ('111', 'The Roofing Standard LLC'),
  ('117', 'Thousand Islands Winery'),
  ('122-123, 143', 'Timberland Fence'),
  ('93', 'T-Mobile'),
  ('195-196', 'Tru-Line Hardwood Flooring'),
  ('144', 'Tupperware'),
  ('2', 'Uniquely Yours'),
  ('49', 'Upstate Spray Foam Insulation'),
  ('89', 'Utica Gutters'),
  ('17-18', 'W&B New York'),
  ('147', 'Weis Vineyards'),
  ('1', 'WellsServices Inc.'),
  ('24', 'Wish Fairy'),
  ('149', 'Witch''s Wicked Treats'),
  ('31', 'Woodford Bros., Inc.'),
  ('186', 'Yorkville Framing & Supply Co.')
) AS m(booth_number, company)
JOIN vendors ve ON ve.company_name = m.company
WHERE b.booth_number = m.booth_number;
